server:
  port: 8090
security:
  oauth2:
    client:
      client-id: app
      client-secret: app
      access-token-uri: http://localhost:8089/oauth/token
      user-authorization-uri: http://localhost:8089/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8089/oauth/token_key
        key-value: iot

spring:
  application:
    name: oauth2-resource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/m1
    username: root
    password: '!Qazxsw2'
