server:
  port: 8090
security:
  oauth2:
    client:
      client-id: app
      client-secret: app
      access-token-uri: http://localhost:8089/oauth/token
      user-authorization-uri: http://localhost:8089/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8089/oauth/token_key
        key-value: iot
