logging:
  level:
    com:
      example:
        demo:
          pingshi:
            session: debug
server:
  port: 8888

spring:
  output:
    ansi:
      enabled: always
  datasource:
    username: root
    password: '!Qazxsw2'
    url: jdbc:mysql://localhost:3306/employees
    driver-class-name: com.mysql.cj.jdbc.Driver

conn:
  remoteIP: 196.0.0.0
  name: root
  password: mypassword

remote:
  connection:
    ip: 111.111.111.111
    name: test
    password: aaa
    enabled: true

