logging:
  level:
    com:
      example:
        demo:
          pingshi:
            session: debug
server:
  port: 8888

spring:
  output:
    ansi:
      enabled: always


conn:
  remoteIP: 196.0.0.0
  name: root
  password: mypassword
