server:
  port: 8989

spring:
  output:
    ansi:
      enabled: always
  datasource:
    username: root
    password: '!Qazxsw2'
    url: jdbc:mysql://localhost:3306/employees
    driver-class-name: com.mysql.cj.jdbc.Driver

minio:
  bucketPolicy: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:GetBucketLocation","s3:ListBucket","s3:ListBucketMultipartUploads"],"Resource":["arn:aws:s3:::iot"]},{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:DeleteObject","s3:GetObject","s3:ListMultipartUploadParts","s3:PutObject","s3:AbortMultipartUpload"],"Resource":["arn:aws:s3:::iot/*"]}]}'
  prefixPath: /src/main/resources/defaultImage
  bucketName: iot
  accessKey: OKw3bxT5me
  secretKey: AnI22zu!vu89FaJ
  endpoint: http://223.223.176.32:30711
  defaultImages:
   /area/default_area.jpg
   - /areaType/default_areaType.jpg
   - /asset/default_asset_G001.jpg
   - /asset/default_asset_G002.jpg
   - /assetType/default_assetType.jpg
   - /deviceType/default_dt_guan05.jpg
   - /deviceType/default_dt_guan10.jpg
